/*
* generated by Xtext
*/
package com.idobjects.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class IdObjectsDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.idobjects.dsl.ui.internal.IdObjectsDslActivator.getInstance().getInjector("com.idobjects.dsl.IdObjectsDsl");
	}
	
}
