/*
* generated by Xtext
*/
package com.idobjects.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IdObjectsDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/idobjects/dsl/parser/antlr/internal/InternalIdObjectsDsl.tokens");
	}
}
