/*
* generated by Xtext
*/
package com.idobjects.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.idobjects.dsl.services.IdObjectsDslGrammarAccess;

public class IdObjectsDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IdObjectsDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.idobjects.dsl.parser.antlr.internal.InternalIdObjectsDslParser createParser(XtextTokenStream stream) {
		return new com.idobjects.dsl.parser.antlr.internal.InternalIdObjectsDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public IdObjectsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IdObjectsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
