/*
 * generated by Xtext
 */
package com.idobjects.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IdObjectsDslRuntimeModule extends com.idobjects.dsl.AbstractIdObjectsDslRuntimeModule {

}
