/*
 * generated by Xtext
 */
package com.idobjects.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IdObjectsDslUiModule extends com.idobjects.dsl.ui.AbstractIdObjectsDslUiModule {
	public IdObjectsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
