/*
* generated by Xtext
*/
package com.idobjects.dsl.ui.contentassist;

import com.idobjects.dsl.ui.contentassist.AbstractIdObjectsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IdObjectsDslProposalProvider extends AbstractIdObjectsDslProposalProvider {

}
